USE [RegReportDB_Prod]
GO

/****** Object:  Table [dbo].[MIFID2_ME_Report]    Script Date: 5/13/2026 1:30:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MIFID2_ME_Report](
	[RegulationReportID] [int] NULL,
	[DateID] [int] NULL,
	[ReportDate] [date] NULL,
	[CID] [int] NULL,
	[RegulationID] [int] NULL,
	[PositionID] [bigint] NULL,
	[InstrumentID] [int] NULL,
	[OpenORClose] [varchar](1) NULL,
	[BuyORSell] [int] NULL,
	[IDType] [int] NULL,
	[IsCopy] [int] NULL,
	[CopyFund] [int] NULL,
	[FundTypeID] [int] NULL,
	[ReportStatus] [varchar](50) NULL,
	[TransactionReferenceNumber] [varchar](50) NULL,
	[TradingVenueTransactionIdentificationCode] [varchar](50) NULL,
	[ExecutingEntityIdentificationCode] [varchar](50) NULL,
	[InvestmentFirmCoveredBy201465EU] [varchar](50) NULL,
	[BuyerIdentificationCodeType] [varchar](50) NULL,
	[BuyerNPCode] [varchar](50) NULL,
	[BuyerIdentificationCode] [nvarchar](50) NULL,
	[BuyerCountryOfTheBranch] [varchar](50) NULL,
	[BuyerFirstNames] [nvarchar](200) NULL,
	[BuyerSurnames] [nvarchar](200) NULL,
	[BuyerDateOfBirth] [varchar](50) NULL,
	[BuyerDecisionMakerCodeType] [varchar](50) NULL,
	[BuyerDecisionMakerNPCode] [varchar](50) NULL,
	[BuyerDecisionMakerCode] [varchar](50) NULL,
	[BuyerDecisionMakerFirstNames] [varchar](50) NULL,
	[BuyerDecisionMakerSurnames] [varchar](50) NULL,
	[BuyerDecisionMakerDateOfBirth] [varchar](50) NULL,
	[SellerIdentificationCodeType] [varchar](50) NULL,
	[SellerNPCode] [varchar](50) NULL,
	[SellerIdentificationCode] [nvarchar](50) NULL,
	[SellerCountryOfTheBranch] [varchar](50) NULL,
	[SellerFirstNames] [nvarchar](200) NULL,
	[SellerSurnames] [nvarchar](200) NULL,
	[SellerDateOfBirth] [varchar](50) NULL,
	[SellerDecisionMakerCodeType] [varchar](50) NULL,
	[SellerDecisionMakerNPCode] [varchar](50) NULL,
	[SellerDecisionMakerCode] [varchar](50) NULL,
	[SellerDecisionMakerFirstNames] [varchar](50) NULL,
	[SellerDecisionMakerSurnames] [varchar](50) NULL,
	[SellerDecisionMakerDateOfBirth] [varchar](50) NULL,
	[TransmissionOfOrderIndicator] [varchar](50) NULL,
	[TransmittingFirmIdentificationCodeForTheBuyer] [varchar](50) NULL,
	[TransmittingFirmIdentificationCodeForTheSeller] [varchar](50) NULL,
	[TradingDateTime] [varchar](50) NULL,
	[TradingCapacity] [varchar](50) NULL,
	[QuantityType] [varchar](50) NULL,
	[Quantity] [varchar](50) NULL,
	[QuantityCurrency] [varchar](50) NULL,
	[DerivativeNotionalIncreaseDecrease] [varchar](50) NULL,
	[PriceType] [varchar](50) NULL,
	[Price] [varchar](50) NULL,
	[PriceCurrency] [varchar](50) NULL,
	[NetAmount] [varchar](50) NULL,
	[Venue] [varchar](50) NULL,
	[CountryOfTheBranchMembership] [varchar](50) NULL,
	[UpfrontPayment] [varchar](50) NULL,
	[UpfrontPaymentCurrency] [varchar](50) NULL,
	[ComplexTradeComponentId] [varchar](50) NULL,
	[InstrumentIdentificationCode] [varchar](50) NULL,
	[InstrumentFullName] [varchar](400) NULL,
	[InstrumentClassification] [varchar](50) NULL,
	[NotionalCurrency1] [varchar](50) NULL,
	[NotionalCurrency2] [varchar](50) NULL,
	[PriceMultiplier] [varchar](50) NULL,
	[UnderlyingInstrumentCode] [varchar](50) NULL,
	[UnderlyingIndexName] [varchar](50) NULL,
	[TermOfTheUnderlyingIndex] [varchar](50) NULL,
	[OptionType] [varchar](50) NULL,
	[StrikePriceType] [varchar](50) NULL,
	[StrikePrice] [varchar](50) NULL,
	[StrikePriceCurrency] [varchar](50) NULL,
	[OptionExerciseStyle] [varchar](50) NULL,
	[MaturityDate] [varchar](50) NULL,
	[ExpiryDate] [varchar](50) NULL,
	[DeliveryType] [varchar](50) NULL,
	[InvestmentDecisionWithinFirmType] [varchar](50) NULL,
	[InvestmentDecisionWithinFirmNPCode] [varchar](50) NULL,
	[InvestmentDecisionWithinFirm] [nvarchar](200) NULL,
	[CountryOfTheBranchResponsibleForThePersonMakingTheInvestmentDecision] [varchar](50) NULL,
	[ExecutionWithinFirmType] [varchar](50) NULL,
	[ExecutionWithinFirmNPCode] [varchar](50) NULL,
	[ExecutionWithinFirm] [varchar](50) NULL,
	[CountryOfTheBranchSupervisingThePersonResponsibleForTheExecution] [varchar](50) NULL,
	[WaiverIndicator] [varchar](50) NULL,
	[ShortSellingIndicator] [varchar](50) NULL,
	[OTCPostTradeIndicator] [varchar](50) NULL,
	[CommodityDerivativeIndicator] [varchar](50) NULL,
	[SecuritiesFinancingTransactionIndicator] [varchar](50) NULL,
	[BranchLocation] [varchar](50) NULL,
	[TransactionType] [varchar](50) NULL,
	[LifecycleEvent] [varchar](50) NULL,
	[AssetClass] [varchar](100) NULL,
	[IsRealStockETF] [int] NULL,
	[UpdateDate] [datetime] NULL,
	[BackReportingIndicator] [smallint] NULL,
	[RegChange] [int] NULL
) ON [Data]
WITH
(
DATA_COMPRESSION = PAGE
)
GO

