USE [RegReportDB_Prod]
GO

/****** Object:  Table [dbo].[ASIC2_Transactions]    Script Date: 5/15/2026 3:07:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ASIC2_Transactions](
	[DateID] [int] NOT NULL,
	[ReportDate] [datetime] NOT NULL,
	[CID] [int] NOT NULL,
	[RegulationID] [int] NULL,
	[RegChange] [int] NOT NULL,
	[Order] [nvarchar](25) NOT NULL,
	[InstrumentID] [int] NOT NULL,
	[Symbol] [nvarchar](25) NULL,
	[ISIN] [nvarchar](50) NULL,
	[PositionID] [bigint] NOT NULL,
	[OpenORClose] [nvarchar](25) NOT NULL,
	[IsBuy] [nvarchar](25) NULL,
	[OpenPrice] [nvarchar](25) NULL,
	[Quantity] [nvarchar](25) NULL,
	[Hedge_Client] [nvarchar](50) NULL,
	[Level] [nvarchar](50) NULL,
	[UpdateDate] [datetime] NULL,
	[ReportingJurisdiction] [nvarchar](50) NULL,
	[Uncollateralised] [nvarchar](50) NULL,
	[UTI] [nvarchar](50) NULL,
	[Unique_product_identifier_UPI] [nvarchar](50) NULL,
	[Asset_class] [nvarchar](50) NULL,
	[Contract_type] [nvarchar](50) NULL,
	[Entity_responsible_for_reporting] [nvarchar](50) NULL,
	[CDE_Counterparty_1_reporting_counterparty] [nvarchar](50) NULL,
	[CDE_Counterparty_2] [nvarchar](50) NULL,
	[Counterparty_2_name] [nvarchar](105) NULL,
	[CDE_Counterparty_2_identifier_type] [nvarchar](50) NULL,
	[Country_of_counterparty_2] [nvarchar](50) NULL,
	[CDE_Beneficiary_1] [nvarchar](50) NULL,
	[CDE_Beneficiary_1_type] [nvarchar](50) NULL,
	[Broker_ID] [nvarchar](50) NULL,
	[Execution_agent_of_Counterparty_1] [nvarchar](50) NULL,
	[CDE_Direction_1_Buyer_identifier_Seller_identifier] [nvarchar](50) NULL,
	[CDE_Direction_2_Payer_identifier_Receiver_identifier_of_leg_1] [nvarchar](50) NULL,
	[CDE_Direction_2_Payer_identifier_Receiver_identifier_of_leg_2] [nvarchar](50) NULL,
	[CDE_Effective_date] [nvarchar](50) NULL,
	[CDE_Expiration_date] [nvarchar](50) NULL,
	[CDE_Execution_timestamp] [nvarchar](50) NULL,
	[CDE_Event_timestamp] [nvarchar](50) NULL,
	[Clearing_timestamp] [nvarchar](50) NULL,
	[CDE_Cleared] [nvarchar](50) NULL,
	[CDE_Central_counterparty] [nvarchar](50) NULL,
	[CDE_Clearing_member] [nvarchar](50) NULL,
	[CDE_Platform_identifier] [nvarchar](50) NULL,
	[CDE_Notional_amount_of_leg_1] [nvarchar](50) NULL,
	[CDE_Notional_amount_of_leg_2] [nvarchar](50) NOT NULL,
	[CDE_Total_notional_quantity_of_leg_1] [nvarchar](50) NULL,
	[CDE_Total_notional_quantity_of_leg_2] [nvarchar](50) NULL,
	[Notional_quantity_Leg_1] [nvarchar](50) NULL,
	[Notional_quantity_Leg_2] [nvarchar](50) NULL,
	[CDE_Call_amount] [nvarchar](50) NULL,
	[CDE_Put_amount] [nvarchar](50) NULL,
	[CDE_Notional_currency_1] [nvarchar](50) NULL,
	[CDE_Notional_currency_2] [nvarchar](50) NULL,
	[CDE_Quantity_unit_of_measure_Leg_1] [nvarchar](50) NULL,
	[CDE_Quantity_unit_of_measure_Leg_2] [nvarchar](50) NULL,
	[CDE_Call_currency] [nvarchar](50) NULL,
	[CDE_Put_currency] [nvarchar](50) NULL,
	[CDE_Effective_date_of_notional_amount_of_leg_1] [nvarchar](50) NULL,
	[CDE_End_date_of_notional_amount_of_leg_1] [nvarchar](50) NULL,
	[CDE_Notional_amount_in_effect_on_associated_effective_date_of_leg_1] [nvarchar](50) NULL,
	[CDE_Effective_date_of_notional_amount_of_leg_2] [nvarchar](50) NULL,
	[CDE_End_date_of_notional_amount_of_leg_2] [nvarchar](50) NULL,
	[CDE_Notional_amount_in_effect_on_associated_effective_date_of_leg_2] [nvarchar](50) NULL,
	[CDE_Price_notation] [nvarchar](50) NULL,
	[CDE_Price] [nvarchar](50) NULL,
	[CDE_Price_currency] [nvarchar](50) NULL,
	[CDE_Price_unit_of_measure] [nvarchar](50) NULL,
	[CDE_Fixed_rate_of_leg_1_coupon] [nvarchar](50) NULL,
	[CDE_Fixed_rate_of_leg_2] [nvarchar](50) NULL,
	[CDE_Spread_notation_of_leg_1] [nvarchar](50) NULL,
	[CDE_Spread_of_leg_1] [nvarchar](50) NULL,
	[CDE_Spread_notation_of_leg_2] [nvarchar](50) NULL,
	[CDE_Spread_of_leg_2] [nvarchar](50) NULL,
	[CDE_Spread_currency_of_leg_1] [nvarchar](50) NULL,
	[CDE_Spread_currency_of_leg_2] [nvarchar](50) NULL,
	[CDE_Strike_price_notation] [nvarchar](50) NULL,
	[CDE_Strike_price] [nvarchar](50) NULL,
	[CDE_Strike_price_currency] [nvarchar](50) NULL,
	[CDE_Strike_price_currency_2] [nvarchar](50) NULL,
	[CDE_Option_premium_amount] [nvarchar](50) NULL,
	[CDE_Option_premium_currency] [nvarchar](50) NULL,
	[CDE_Option_premium_payment_date] [nvarchar](50) NULL,
	[CDE_Exchange_rate] [nvarchar](50) NULL,
	[CDE_Exchange_rate_basis_currency_1] [nvarchar](50) NULL,
	[CDE_Exchange_rate_basis_currency_2] [nvarchar](50) NULL,
	[CDE_Fixed_rate_coupon_day_count_convention_leg_1] [nvarchar](50) NULL,
	[CDE_Floating_rate_day_count_convention_of_leg_1] [nvarchar](50) NULL,
	[CDE_Fixed_rate_day_count_convention_leg_2] [nvarchar](50) NULL,
	[CDE_Floating_rate_day_count_convention_of_leg_2] [nvarchar](50) NULL,
	[CDE_Fixed_rate_coupon_payment_frequency_period_leg_1] [nvarchar](50) NULL,
	[CDE_Floating_rate_payment_frequency_period_of_leg_1] [nvarchar](50) NULL,
	[CDE_Fixed_rate_payment_frequency_period_leg_2] [nvarchar](50) NULL,
	[CDE_Floating_rate_payment_frequency_period_of_leg_2] [nvarchar](50) NULL,
	[CDE_Fixed_rate_coupon_payment_frequency_period_multiplier_leg_1] [nvarchar](50) NULL,
	[CDE_Floating_rate_payment_frequency_period_multiplier_of_leg_1] [nvarchar](50) NULL,
	[CDE_Fixed_rate_payment_frequency_period_multiplier_leg_2] [nvarchar](50) NULL,
	[CDE_Floating_rate_payment_frequency_period_multiplier_of_leg_2] [nvarchar](50) NULL,
	[CDE_Settlement_currency_1] [nvarchar](50) NULL,
	[CDE_Settlement_currency_2] [nvarchar](50) NULL,
	[CDE_Other_payment_amount] [nvarchar](50) NULL,
	[CDE_Other_payment_type] [nvarchar](50) NULL,
	[CDE_Other_payment_currency] [nvarchar](50) NULL,
	[CDE_Other_payment_date] [nvarchar](50) NULL,
	[CDE_Other_payment_payer] [nvarchar](50) NULL,
	[CDE_Other_payment_receiver] [nvarchar](50) NULL,
	[Custom_basket_code_Identifier_LEI] [nvarchar](50) NULL,
	[CDE_Identifier_of_baskets_constituents] [nvarchar](50) NULL,
	[CDE_Source_of_identifier_of_baskets_constituents] [nvarchar](50) NULL,
	[Underlying_identification] [nvarchar](50) NULL,
	[Underlying_identification_type] [nvarchar](50) NULL,
	[Maturity_date_of_underlying] [nvarchar](50) NULL,
	[Indicator_of_floating_rate_of_leg_2] [nvarchar](50) NULL,
	[Floating_rate_reference_period_of_leg_2_time_period] [nvarchar](50) NULL,
	[Floating_rate_reference_period_of_leg_2_multiplier] [nvarchar](50) NULL,
	[CDE_CDS_index_attachment_point] [nvarchar](50) NULL,
	[CDE_CDS_index_detachment_point] [nvarchar](50) NULL,
	[Index_factor] [nvarchar](50) NULL,
	[CDE_Package_identifier] [nvarchar](50) NULL,
	[Swap_link_ID] [nvarchar](50) NULL,
	[CDE_Package_transaction_price_notation] [nvarchar](50) NULL,
	[CDE_Package_transaction_price] [nvarchar](50) NULL,
	[CDE_Package_transaction_price_currency] [nvarchar](50) NULL,
	[CDE_Package_transaction_spread_notation] [nvarchar](50) NULL,
	[CDE_Package_transaction_spread] [nvarchar](50) NULL,
	[CDE_Package_transaction_spread_currency] [nvarchar](50) NULL,
	[CDE_Prior_UTI] [nvarchar](50) NULL,
	[Event_Identifier] [nvarchar](50) NULL,
	[Action_type] [nvarchar](50) NULL,
	[Event_type] [nvarchar](50) NULL,
	[Report_submitting_entity_ID] [nvarchar](50) NULL,
	[Initial_margin_collateral_portfolio_code] [nvarchar](50) NULL,
	[Variation_margin_collateral_portfolio_code] [nvarchar](50) NULL,
	[CDE_Collateral_portfolio_indicator] [nvarchar](50) NULL,
	[Technical_Record_Identification] [nvarchar](50) NULL,
	[CDE_Reporting_timestamp] [nvarchar](50) NULL,
	[Secondary_transaction_identifier] [nvarchar](50) NULL,
	[New_Derivative_Trade_Repository] [nvarchar](50) NULL,
	[Single_lower_barrier_price_notation] [nvarchar](50) NULL,
	[Upper_barrier_price_notation] [nvarchar](50) NULL,
	[Single_lower_barrier_price] [nvarchar](50) NULL,
	[Upper_barrier_price] [nvarchar](50) NULL,
	[Single_lower_barrier_price_currency] [nvarchar](50) NULL,
	[Upper_barrier_price_currency] [nvarchar](50) NULL
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)
GO

